name: nadek
version: 1.1.8+12
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  http: ^0.13.6
  http_auth: ^1.0.2
  bloc: ^8.1.2
  flutter_offline: ^3.0.0
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  awesome_bottom_bar: ^1.2.3
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.2.0
  is_first_run: ^1.0.0
  shared_preferences: ^2.2.0
  video_player: ^2.7.0
  path_provider: ^2.0.15
  lazy_load_indexed_stack: ^1.0.1
  connection_notifier: ^1.0.1
  dropdown_search: ^5.0.6
  connectivity_plus: ^5.0.2
  table_calendar: ^3.0.9
  time_range: ^1.1.0
  flutter_local_notifications: ^15.1.0+1
  progress_dialog_null_safe: ^1.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
#  location: ^5.0.0
  date_format: ^2.0.7
  date_field: ^3.0.5
  badges: ^3.1.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  modal_progress_hud_nsn: ^0.4.0
  image_picker: ^1.0.1
  google_maps_flutter: ^2.4.0
  custom_marker: ^1.0.0
  ndialog: ^4.3.1
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  chips_choice: ^3.0.0
  uuid: ^3.0.7
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.5
  flutter_paypal: 0.2.0
  share_plus: ^7.2.1
  flutter_phoenix: ^1.1.1
  country_code_picker: ^3.0.0
  flutter_advanced_drawer: ^1.3.5
  equatable:
  story_view:

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

  flutter_test: 
    sdk: flutter
    
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"



flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/icons/socialmedia/
    
  fonts: 
    - family: Schyler
      fonts: 
        - asset: assets/font/ubunt-arabic.ttf
  uses-material-design: true

